nums=[10,34,56,78,43,23,45,67,10]
print("List of Numbers :",nums)
nums.append(23)
print("append 23:",nums)
nums.extend([4,56,78])
print("Extend with 4,56,78:",nums)
nums.insert(3,15)
print("insert 15 at 3rd index 3:",nums)
nums.remove(78)
print("remove 78:",nums)
nums.pop(2)
print("pop 2nd index:",nums)
print("index of 43:",nums.index(43))
print("count how many 23:",nums.count(23))
nums.sort()
print("sort the list:",nums)
nums.reverse()
print("reverse the list:",nums)
numbers=nums.copy()
print("copy the list:",numbers)
print("length of the list:",len(nums))
print("maximum number of the list:",max(nums))
print("mininum number of the list:",min(nums))
print("sum of the number in the list:",sum(nums))
